=== cianfrocco-lab/COSMIC-CryoEM-Gateway/gateway_config/sdk/src/main/resources/pisexml/pise2.dtd
<!-- DTD for Pise descriptions
     Copyright (C) 1999-2204 Institut Pasteur and Catherine Letondal <letondal@pasteur.fr> 
  -->
<!ENTITY % word "CDATA">
<!ENTITY % number "CDATA">
<!ENTITY % boolean "CDATA">
<!ELEMENT pise (head, command, parameters)>
<!ELEMENT command (#PCDATA)>
<!ELEMENT parameters (parameter)+>
<!ELEMENT head (title, version?, description?, authors?, reference*, category*, doclink*)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT doclink (#PCDATA)>
<!ELEMENT authors (#PCDATA)>
<!ELEMENT reference (#PCDATA)>
<!ELEMENT parameter (paragraph | (name, attributes)+)>
<!ELEMENT paragraph (name, prompt, precond?, group?, format?, comment?, parameters)>
<!ATTLIST parameter
	type (InFile | Sequence | OutFile | Results | Switch | Excl | List | Integer | Float | String | Paragraph | Label) #REQUIRED
	ismandatory %boolean; #IMPLIED
	iscommand %boolean; #IMPLIED
	ishidden %boolean; #IMPLIED
	isstandout %boolean; #IMPLIED
	issimple %boolean; #IMPLIED
	isclean %boolean; #IMPLIED
	isinput %boolean; #IMPLIED
>
<!ELEMENT attributes (prompt | info | format | vdef | group | vlist | flist | comment | seqfmt | seqtype | ctrls | warns | precond | paramfile | filenames | scalemin | scalemax | scaleinc | separator | size | pipe | withpipe)+>
<!ELEMENT prompt (#PCDATA)>
<!ELEMENT format (language, code)+>
<!ELEMENT vdef ((value)+ | (language, code)+)>
<!ELEMENT group (#PCDATA)>
<!ELEMENT info (#PCDATA)>
<!ELEMENT vlist (value, label)+>
<!ELEMENT flist (value, code)+>
<!ELEMENT comment (value)+>
<!ELEMENT seqfmt (value)+>
<!ELEMENT seqtype (value | (language, code)+)>
<!ELEMENT ctrls (ctrl)+>
<!ELEMENT ctrl (message, (language, code)+)>
<!ELEMENT warns (warn)+>
<!ELEMENT warn (message, (language, code)+)>
<!ELEMENT message (#PCDATA)>
<!ELEMENT precond (language, code)+>
<!ELEMENT paramfile (#PCDATA)>
<!ELEMENT filenames (#PCDATA)>
<!ELEMENT scalemin (value | (language, code)+)>
<!ELEMENT scalemax (value | (language, code)+)>
<!ELEMENT scaleinc (#PCDATA)>
<!ELEMENT separator (#PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT pipe (pipetype, (language, code)+)+>
<!ELEMENT withpipe (pipetype, (parametername)+)+>
<!ELEMENT parametername (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT pipetype (#PCDATA)>
<!ELEMENT label (#PCDATA)>
<!ELEMENT language (#PCDATA)>

=== cianfrocco-lab/COSMIC-CryoEM-Gateway/gateway_config/sdk/src/main/resources/pisexml/alphafoldmultimer.xml
<?xml version = "1.0" encoding = "UTF-8" ?>
<!DOCTYPE pise PUBLIC "pise2.dtd" "pise2.dtd"  [
<!ENTITY runtime_tg PUBLIC "run_time2.xml.in" "run_time2.xml.in" >
]>
<!-- Created by Mark Miller for CryoEM project around 5/24/2016-->
<pise>
  <head>
    <title>AlphaFold2 Multimer</title>
    <version>1.0</version>
    <description>Highly accurate protein structure prediction with AlphaFold Multimer</description>
    <authors>Evans et al. </authors>
    <reference>https://www.biorxiv.org/content/10.1101/2021.10.04.463034v1</reference>
    <category>Protein structure prediction</category>
    <doclink>https://github.com/deepmind/alphafold</doclink>
  </head>

  <command>alphafoldmultimer</command>

<parameters>
<!-- command name: this parameter precedes all instruction strings -->
    <parameter ishidden="1" type="String"> 
	  <name>relion_invoke</name>
	  <attributes>
	    <format>
		  <language>perl</language>
		  <code>"alphafold2multimer"</code>
		</format>
		<group>0</group>
	  </attributes>
	</parameter> 
	  
<!-- build the conf file -->
	<parameter ishidden="1" type="String">
		<name>relion_scheduler</name>
		<attributes>
			<paramfile>scheduler.conf</paramfile>
			<format>
				<language>perl</language>
				<code>
<!-- RUN THESE JOBS ON Comet -->
				 "gpu=2\\n" . 
				 "runhours=12\\n" . 
			     "ntasks-per-node=1\\n" .
				 "nodes=1\\n"
				</code>
			</format>
			<group>1</group>
		</attributes>
	</parameter>	

<!-- create the non-configurable command line -->
<!--  -->
	<parameter ishidden="1" type="String">
		<name>relion_commandline</name>
		<attributes>
			<group>1</group>
		</attributes>
	</parameter>	

<!-- required input file, this is selected outside the parameters gui -->
    <parameter isinput = "1" type = "InFile">
	  <name>infile</name>
	  <attributes>
	    <prompt>FASTA file</prompt>
		<format>
		  <language>perl</language>
		  <code>"--fasta_paths=\"$value\""</code>
		</format>
	    <group>90</group>
	  </attributes>	  
	</parameter>
	
    <parameter type="Results">
      <name>stderr.txt</name>
      <attributes>
        <filenames>stderr</filenames>
      </attributes>
    </parameter>

	<parameter type="Results">
      <name>Input FASTA file</name>
      <attributes>
        <filenames>*.fasta</filenames>
      </attributes>
    </parameter>

    <parameter type="Results">
      <name>Predicted structural models</name>
      <attributes>
        <filenames>output_dir/*/*relaxed*pdb</filenames>
      </attributes>
    </parameter>

	<parameter type="Results">
      <name>Diagnostic plots for each predicted model</name>
      <attributes>
        <filenames>output_dir/*/*.png</filenames>
      </attributes>
    </parameter>

	<parameter type="Results">
      <name>Full output from AlphaFold (compressed)</name>
      <attributes>
        <filenames>*.tar.gz</filenames>
      </attributes>
    </parameter>

	<parameter type="Results">
      <name>Ranking of AlphaFold models</name>
      <attributes>
        <filenames>output_dir/*/*anking_debug.json</filenames>
      </attributes>
    </parameter>

<!-- visible input parameters -->	

	<parameter type="Excl" issimple="1" ismandatory="1">
	    <name>db_preset</name>
	    <attributes>
		    <group>1</group>
		    <prompt>Database</prompt>
		    <format>
			    <language>perl</language>
			    <code>"--db_preset=$value"</code>
		    </format>
            <vdef>
                <value>full_dbs</value>
            </vdef>
            <vlist>
                <value>reduced_dbs</value>
                <label>reduced_dbs</label>
                <value>full_dbs</value>
                <label>full_dbs</label>
            </vlist>
	    </attributes>
    </parameter>
	<parameter type="Excl" issimple="1" ismandatory="1" ishidden="1">
	    <name>model_preset</name>
	    <attributes>
		    <group>1</group>
		    <prompt>Database</prompt>
		    <format>
			    <language>perl</language>
			    <code>"--model_preset=multimer"</code>
		    </format>
            <vdef>
                <value>multimer</value>
            </vdef>
            <vlist>
                <value>monomer</value>
                <label>monomer</label>
                <value>monomer_casp14</value>
                <label>monomer_casp14</label>
                <value>monomer_ptm</value>
                <label>monomer_ptm</label>
                <value>multimer</value>
                <label>multimer</label>
            </vlist>
	    </attributes>
    </parameter>
    <parameter type="Switch" issimple="1" ismandatory="1" ishidden="1">
        <name>relaxrun</name>
        <attributes>
            <group>1</group>
            <prompt>Skip calculating relaxed models</prompt>
            <format>
                <language>perl</language>
                <code>" --relaxrun=False"</code>
            </format>
            <vdef>
                <value>1</value>
            </vdef>
        </attributes>
    </parameter>

</parameters>

</pise>

=== cianfrocco-lab/COSMIC-CryoEM-Gateway/gateway_config/sdk/src/main/resources/pisexml/isonet.xml
<?xml version = "1.0" encoding = "UTF-8" ?>
<!DOCTYPE pise PUBLIC "pise2.dtd" "pise2.dtd"  [
<!ENTITY runtime_tg PUBLIC "run_time2.xml.in" "run_time2.xml.in" >
]>
<!-- Created by Mark Miller for CryoEM project around 5/24/2016-->
<pise>
  <head>
    <title>IsoNet - Refine</title>
    <version>0.2</version>
    <description>Isotropic Reconstruction of Electron Tomograms with Deep Learning</description>
    <authors>Yun-Tao Liu, Heng Zhang, Hui Wang, Chang-Lu Tao, Guo-Qiang Bi, Z. Hong Zhou</authors>
    <reference>https://www.biorxiv.org/content/10.1101/2021.07.17.452128v1</reference>
    <category>Cryo-electron tomography</category>
  </head>

  <command>isonet</command>
<!-- 
Per our conversation earlier today, I’m sending along a comet submission script for the analysis routine that will be a part of the gateway. 

First, you can look at an example submission script that I typically have used (‘relion_refine_submission.txt’). The cluster input variables are standard, 
and then there is a single command that will run using MPI. 

The barebones version of the command line input is the following (‘relion_refine_submission_base.txt’). I’ve bolded and underlined the areas that users 
will have to input: 

ibrun -v relion_refine_mpi  —o /path/to/working/directory/[output] -*auto_refine -*split_random_halves —i /path/to/working/directory/[input file] 
-*particle_diameter [user provided] —angpix [user provided] —ref /path/to/working/directory/[user provided] -*ini_high [user provided] -*ctf 
-*flatten_solvent -*zero_mask -*oversampling 1 -*healpix_order 2 -*auto_local_healpix_order 4 -*offset_range [user provided] -*offset_step [user provided] 
—sym [user provided] -*low_resol_join_halves 40 -*norm -*scale  -*j 1 -*memory_per_thread 4

A list of variables that I would change for these test run (or at least an initial list of variables):
—o Output file basename
—i Input file
—particle_diameter Diameter of particle (Angstroms)
—angpix Pixel size of data (A/pix)
—ref 3D model to use as template 
—ini_high Initial filter for 3D volume
—offset_range Pixel search range 
—offset_step Pixel search range step size
—sym Symmetry of sample 
I’m not sure what the next steps are for building out this command, but this is a definite start. There will be a few added changes to the submission command based upon users data, which we will incorporate into the gateway job template page.

Let me know what else I can do to help!
Mike -->

<parameters>
<!-- command name: this parameter precedes all instruction strings -->
    <parameter ishidden="1" type="String"> 
	  <name>relion_invoke</name>
	  <attributes>
	    <format>
		  <language>perl</language>
		  <code>"isonet"</code>
		</format>
		<group>0</group>
	  </attributes>
	</parameter> 
	  
<!-- build the conf file -->
	<parameter ishidden="1" type="String">
		<name>relion_scheduler</name>
		<attributes>
			<paramfile>scheduler.conf</paramfile>
			<format>
				<language>perl</language>
				<code>
<!-- RUN THESE JOBS ON Comet -->
				 "gpu=4\\n" .
				 "runhours=12\\n" .
				 "ChargeFactor=1.0\\n" .
				 "ntasks-per-node=24\\n" .
				 "node_exclusive=1\\n" .
				 "nodes=1\\n"
				</code>
			</format>
			<group>1</group>
		</attributes>
	</parameter>	

<!-- create the non-configurable command line -->
<!--  -->
	<parameter ishidden="1" type="String">
		<name>relion_commandline</name>
		<attributes>
			<group>1</group>
		</attributes>
	</parameter>	

<!-- required input file, this is selected outside the parameters gui -->
    <parameter isinput = "1" type = "InFile">
	  <name>infile</name>
	  <attributes>
	    <prompt>Image File</prompt>
		<format>
		  <language>perl</language>
		  <code>'"$value"'</code>
		</format>
	    <group>90</group>
	  </attributes>	  
	</parameter>
	
<!-- Files to transfer back -->
	<parameter type="Results">
	  <name>stderr.txt</name>
	  <attributes>
	    <filenames>stderr</filenames>
	  </attributes>
	</parameter>

<!-- visible input parameters -->	

	<parameter type="Excl" issimple="1" ismandatory="1">
        <name>model</name>
        <attributes>
            <group>1</group>
            <prompt>Approach for iterations and denoising</prompt>
            <format>
                <language>perl</language>
                <code>"-p $value"</code>
            </format>
            <vdef>
                <value>Regular</value>
            </vdef>
            <vlist>
                <value>Regular</value>
                <label>Regular</label>
                <value>Exhaustive</value>
                <label>Exhaustive</label>
                <value>Disabled</value>
                <label>Disabled</label>
				<value>Debug</value>
                <label>Debug</label>
            </vlist>
        </attributes>
    </parameter>

</parameters>

</pise>

=== cianfrocco-lab/COSMIC-CryoEM-Gateway/gateway_config/sdk/src/main/resources/pisexml/cryo_efficiency.xml
<?xml version = "1.0" encoding = "UTF-8" ?>
<!DOCTYPE pise PUBLIC "pise2.dtd" "pise2.dtd"  [
<!ENTITY runtime_tg PUBLIC "run_time2.xml.in" "run_time2.xml.in" >
]>
<!-- Created by Mark Miller for CryoEM project around 5/24/2016-->
<pise>
  <head>
    <title>Efficiency (cryoEF)</title>
    <version>1.1.1</version>
    <description>Calculate efficiency for 3D reconstruction to determine if Euler angle coverage is evenly distributed</description>
    <authors>Naydenova and Russo</authors>
    <reference>Naydenova, K and Russo, CJ "Measuring the effects of particle orientation to improve the efficiency of electron cryomicroscopy" Nature Communications (2017)</reference>
    <category>Validation and Analysis</category>
    <doclink>https://www.mrc-lmb.cam.ac.uk/crusso/cryoEF/index.html</doclink>
  </head>

  <command>cryo_efficiency</command>

<parameters>
<!-- command name: this parameter precedes all instruction strings -->
    <parameter ishidden="1" type="String"> 
	  <name>relion_invoke</name>
	  <attributes>
	    <format>
		  <language>perl</language>
		  <code>"/home/cosmic2/software_dependencies/cryoEF/cryoEF_v1.1.0/PreCompiled/centos5.11/cryoEF"</code>
		</format>
		<group>0</group>
	  </attributes>
	</parameter> 
	  
<!-- build the conf file -->
	<parameter ishidden="1" type="String">
		<name>relion_scheduler</name>
		<attributes>
			<paramfile>scheduler.conf</paramfile>
			<format>
				<language>perl</language>
				<code>
<!-- RUN THESE JOBS ON Comet -->
				 "runhours=12\\n" . 
			     "ntasks-per-node=1\\n" .
				 "node_exclusive=1\\n" .
				 "nodes=1\\n"
				</code>
			</format>
			<group>1</group>
		</attributes>
	</parameter>	

<!-- create the non-configurable command line -->
<!--  -->
	<parameter ishidden="1" type="String">
		<name>relion_commandline</name>
		<attributes>
			<group>1</group>
		</attributes>
	</parameter>	

<!-- required input file, this is selected outside the parameters gui -->
    <parameter isinput = "1" type = "InFile">
	  <name>infile</name>
	  <attributes>
	    <prompt>STAR file</prompt>
		<format>
		  <language>perl</language>
		  <code>"-f \"$value\""</code>
		</format>
	    <group>90</group>
	  </attributes>	  
	</parameter>
	
    <parameter type="Results">
      <name>stderr.txt</name>
      <attributes>
        <filenames>stderr</filenames>
      </attributes>
    </parameter>

<!-- visible input parameters -->	

	<parameter type="Excl" issimple="1" ismandatory="1">
	    <name>sym</name>
	    <attributes>
		    <group>1</group>
		    <prompt>Symmetry of sample (sym)</prompt>
		    <format>
			    <language>perl</language>
			    <code>"-g $value"</code>
		    </format>
            <vdef>
                <value>C1</value>
            </vdef>
            <vlist>
                <value>C1</value>
                <label>C1</label>
                <value>Ci</value>
                <label>Ci</label>
                <value>Cs</value>
                <label>Cs</label>
                <value>C2</value>
                <label>C2</label>
                <value>C2v</value>
                <label>C2v</label>
                <value>C2h</value>
                <label>C2h</label>
                <value>C3</value>
                <label>C3</label>
                <value>C3v</value>
                <label>C3v</label>
                <value>C3h</value>
                <label>C3h</label>
                <value>C4</value>
                <label>C4</label>
                <value>C4v</value>
                <label>C4v</label>
                <value>C4h</value>
                <label>C4h</label>
                <value>C5</value>
                <label>C5</label>
                <value>C5v</value>
                <label>C5v</label>
                <value>C5h</value>
                <label>C5h</label>
                <value>C6</value>
                <label>C6</label>
                <value>C6v</value>
                <label>C6v</label>
                <value>C6h</value>
                <label>C6h</label>
                <value>C7</value>
                <label>C7</label>
                <value>C7v</value>
                <label>C7v</label>
                <value>C7h</value>
                <label>C7h</label>
                <value>C8</value>
                <label>C8</label>
                <value>C8v</value>
                <label>C8v</label>
                <value>C8h</value>
                <label>C8h</label>
                <value>C9</value>
                <label>C9</label>
                <value>C9v</value>
                <label>C9v</label>
                <value>C9h</value>
                <label>C9h</label>
                <value>C10</value>
                <label>C10</label>
                <value>C10v</value>
                <label>C10v</label>
                <value>C10h</value>
                <label>C10h</label>
                <value>S1</value>
                <label>S1</label>
                <value>S2</value>
                <label>S2</label>
                <value>S3</value>
                <label>S3</label>
                <value>S4</value>
                <label>S4</label>
                <value>S5</value>
                <label>S5</label>
                <value>S6</value>
                <label>S6</label>
                <value>S7</value>
                <label>S7</label>
                <value>S8</value>
                <label>S8</label>
                <value>S9</value>
                <label>S9</label>
                <value>S10</value>
                <label>S10</label>
                <value>D1</value>
                <label>D1</label>
                <value>D2</value>
                <label>D2</label>
                <value>D3</value>
                <label>D3</label>
                <value>D4</value>
                <label>D4</label>
                <value>D5</value>
                <label>D5</label>
                <value>D6</value>
                <label>D6</label>
                <value>D7</value>
                <label>D7</label>
                <value>D8</value>
                <label>D8</label>
                <value>D9</value>
                <label>D9</label>
                <value>D10</value>
                <label>D10</label>
                <value>D11</value>
                <label>D11</label>
                <value>D12</value>
                <label>D12</label>
                <value>D1v</value>
                <value>D1v</value>
                <label>D2v</label>
                <label>D2v</label>
                <value>D3v</value>
                <label>D3v</label>
                <value>D4v</value>
                <label>D4v</label>
                <value>D5v</value>
                <label>D5v</label>
                <value>D6v</value>
                <label>D6v</label>
                <value>D7v</value>
                <label>D7v</label>
                <value>D8v</value>
                <label>D8v</label>
                <value>D9v</value>
                <label>D9v</label>
                <value>D10v</value>
                <label>D10v</label>
                <value>D11v</value>
                <label>D11v</label>
                <value>D12v</value>
                <label>D12v</label>
                <value>D1h</value>
                <label>D1h</label>
                <value>D2h</value>
                <label>D2h</label>
                <value>D3h</value>
                <label>D3h</label>
                <value>D4h</value>
                <label>D4h</label>
                <value>D5h</value>
                <label>D5h</label>
                <value>D6h</value>
                <label>D6h</label>
                <value>D7h</value>
                <label>D7h</label>
                <value>D8h</value>
                <label>D8h</label>
                <value>D9h</value>
                <label>D9h</label>
                <value>D10h</value>
                <label>D10h</label>
                <value>D11h</value>
                <label>D11h</label>
                <value>D12h</value>
                <label>D12h</label>
                <value>T</value>
                <label>T</label>
                <value>Td</value>
                <label>Td</label>
                <value>Th</value>
                <label>Th</label>
                <value>O</value>
                <label>O</label>
                <value>Oh</value>
                <label>Oh</label>
                <value>I1</value>
                <label>I1</label>
                <value>I2</value>
                <label>I2</label>
                <value>I3</value>
                <label>I3</label>
                <value>I4</value>
                <label>I4</label>
                <value>I5</value>
                <label>I5</label>
                <value>Ih</value>
                <label>Ih</label>
            </vlist>
	    </attributes>
    </parameter>

</parameters>

</pise>

=== cianfrocco-lab/COSMIC-CryoEM-Gateway/gateway_config/sdk/src/main/resources/pisexml/colabfold.xml
<?xml version = "1.0" encoding = "UTF-8" ?>
<!DOCTYPE pise PUBLIC "pise2.dtd" "pise2.dtd"  [
<!ENTITY runtime_tg PUBLIC "run_time2.xml.in" "run_time2.xml.in" >
]>
<!-- Created by Mark Miller for CryoEM project around 5/24/2016-->
<pise>
  <head>
    <title>ColabFold</title>
    <version>1.5.2</version>
    <description>Fast and convenient protein structure predictions using MMseqs2 and AlphaFold</description>
    <authors>Mirdita et al. </authors>
    <reference>https://www.nature.com/articles/s41592-022-01488-1</reference>
    <category>Protein structure prediction</category>
    <doclink>https://github.com/deepmind/alphafold</doclink>
  </head>

  <command>colabfold</command>

<parameters>
<!-- command name: this parameter precedes all instruction strings -->
    <parameter ishidden="1" type="String"> 
	  <name>relion_invoke</name>
	  <attributes>
	    <format>
		  <language>perl</language>
		  <code>"colabfold"</code>
		</format>
		<group>0</group>
	  </attributes>
	</parameter> 
	  
<!-- build the conf file -->
	<parameter ishidden="1" type="String">
		<name>relion_scheduler</name>
		<attributes>
			<paramfile>scheduler.conf</paramfile>
			<format>
				<language>perl</language>
				<code>
<!-- RUN THESE JOBS ON Comet -->
				 "gpus=1\\n" . 
				 "cpus=10\\n" . 
				 "memory=90G\\n" . 
				 "runhours=48\\n" . 
			     "ntasks-per-node=1\\n" .
				 "nodes=1\\n"
				</code>
			</format>
			<group>1</group>
		</attributes>
	</parameter>	

<!-- create the non-configurable command line -->
<!--  -->
	<parameter ishidden="1" type="String">
		<name>relion_commandline</name>
		<attributes>
			<group>1</group>
		</attributes>
	</parameter>	

<!-- required input file, this is selected outside the parameters gui -->
    <parameter isinput = "1" type = "InFile">
	  <name>infile</name>
	  <attributes>
	    <prompt>FASTA file</prompt>
		<format>
		  <language>perl</language>
		  <code>"--fasta_path=\"$value\""</code>
		</format>
	    <group>90</group>
	  </attributes>	  
	</parameter>

	<parameter type="Integer" issimple="1" ismandatory="1">
      <name>num_models</name>
      <attributes>
        <group>1</group>
        <prompt>Number of models</prompt>
        <format>
          <language>perl</language>
          <code>"--num_models=$value"</code>
        </format>
        <vdef>
          <value>5</value>
        </vdef>
        <ctrls>
          <ctrl>
            <message>Please enter an integer > 0 for the number of models to use</message>
            <language>perl</language>
            <code>$num_models &lt; 0</code>
          </ctrl>
        </ctrls>
      </attributes>
    </parameter>

 	<parameter type="Integer" issimple="1" ismandatory="1">
	  <name>num_recycles</name>
	  <attributes>
        <group>1</group>
	    <prompt>Number of Recycles</prompt>
	    <format>
	      <language>perl</language>
	      <code>"--num_recycles=$value"</code>
        </format>
	    <vdef>
	      <value>3</value>
	    </vdef>
	    <ctrls>
	      <ctrl>
	        <message>Please enter an integer > 0 for the number of recycles to use</message>
	        <language>perl</language>
	        <code>$num_recycles &lt; 0</code>
	      </ctrl>
	    </ctrls>
	  </attributes>
	</parameter>
	
	<parameter type="Integer" issimple="1" ismandatory="1">
      <name>stop_score</name>
      <attributes>
        <group>1</group>
        <prompt>Stop at score (Compute recycle models until plddt (single chain) or ptmscore (complex) > threshold is reached.) Leave blank to use all recyles.</prompt>
        <format>
          <language>perl</language>
          <code>"--stop_at_score=$value"</code>
        </format>
		<vdef>
          <value>80</value>
        </vdef>
      </attributes>
    </parameter>

 	<parameter type="Switch">
	  <name>use_amber</name>
	  <attributes>
        <group>1</group>
	    <prompt>Use Amber molecular dynamics relaxation?</prompt>
	    <format>
	      <language>perl</language>
	      <code>"--use_amber=$value"</code>
        </format>
	    <vdef>
	      <value>0</value>
	    </vdef>
	  </attributes>
	</parameter>

 	<parameter type="Switch" issimple="1">
	  <name>use_templates</name>
	  <attributes>
        <group>1</group>
	    <prompt>Use templates from published PDB structures?</prompt>
	    <format>
	      <language>perl</language>
	      <code>"--use_templates=$value"</code>
        </format>
	    <vdef>
	      <value>0</value>
	    </vdef>
	  </attributes>
	</parameter>

	<parameter type="Excl" ismandatory="1" ishidden="0">
        <name>maxmsa</name>
        <attributes>
            <group>1</group>
            <prompt>Max MSA depth (smaller values to increase uncertainty)</prompt>
            <format>
                <language>perl</language>
                <code>"--max_msa=$maxmsa"</code>
            </format>
            <vdef>
                <value>auto</value>
            </vdef>
            <vlist>
                <value>auto</value>
                <label>auto</label>
                <value>512:1024</value>
                <label>512:1024</label>
                <value>256:512</value>
                <label>256:512</label>
                <value>64:128</value>
                <label>64:128</label>
				<value>32:64</value>
                <label>32:64</label>
				<value>16:32</value>
                <label>16:32</label>
            </vlist>
        </attributes>
    </parameter>

    <parameter type="Results">
      <name>stderr.txt</name>
      <attributes>
        <filenames>stderr</filenames>
      </attributes>
    </parameter>

	<parameter type="Results">
      <name>Input FASTA file</name>
      <attributes>
        <filenames>*.fasta</filenames>
      </attributes>
    </parameter>

    <parameter type="Results">
      <name>Predicted structural models</name>
      <attributes>
        <filenames>output/*relaxed*pdb</filenames>
      </attributes>
    </parameter>

	<parameter type="Results">
      <name>Diagnostic plots for each predicted model</name>
      <attributes>
        <filenames>output/*.png</filenames>
      </attributes>
    </parameter>

	<parameter type="Results">
      <name>Full output from AlphaFold (compressed)</name>
      <attributes>
        <filenames>*.tar.gz</filenames>
      </attributes>
    </parameter>

	<parameter type="Results">
      <name>Ranking of AlphaFold models</name>
      <attributes>
        <filenames>output/*scores.json</filenames>
      </attributes>
    </parameter>

	<parameter type="Results">
      <name>Predicted error of AlphaFold models</name>
      <attributes>
        <filenames>output/*error_v1.json</filenames>
      </attributes>
    </parameter>

	<parameter type="Results">
      <name>Citation file</name>
      <attributes>
        <filenames>output/cite.bibtex</filenames>
      </attributes>
    </parameter>
<!--
	<parameter type="Results">
      <name>A3M</name>
      <attributes>
        <filenames>output_dir/*.a3m</filenames>
      </attributes>
    </parameter>
 -->

<!-- visible input parameters -->	


</parameters>

</pise>
