=== cianfrocco-lab/COSMIC-CryoEM-Gateway/gateway_config/sdk/src/main/resources/pisexml/pise2.dtd
<!-- DTD for Pise descriptions
     Copyright (C) 1999-2204 Institut Pasteur and Catherine Letondal <letondal@pasteur.fr> 
  -->
<!ENTITY % word "CDATA">
<!ENTITY % number "CDATA">
<!ENTITY % boolean "CDATA">
<!ELEMENT pise (head, command, parameters)>
<!ELEMENT command (#PCDATA)>
<!ELEMENT parameters (parameter)+>
<!ELEMENT head (title, version?, description?, authors?, reference*, category*, doclink*)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT doclink (#PCDATA)>
<!ELEMENT authors (#PCDATA)>
<!ELEMENT reference (#PCDATA)>
<!ELEMENT parameter (paragraph | (name, attributes)+)>
<!ELEMENT paragraph (name, prompt, precond?, group?, format?, comment?, parameters)>
<!ATTLIST parameter
	type (InFile | Sequence | OutFile | Results | Switch | Excl | List | Integer | Float | String | Paragraph | Label) #REQUIRED
	ismandatory %boolean; #IMPLIED
	iscommand %boolean; #IMPLIED
	ishidden %boolean; #IMPLIED
	isstandout %boolean; #IMPLIED
	issimple %boolean; #IMPLIED
	isclean %boolean; #IMPLIED
	isinput %boolean; #IMPLIED
>
<!ELEMENT attributes (prompt | info | format | vdef | group | vlist | flist | comment | seqfmt | seqtype | ctrls | warns | precond | paramfile | filenames | scalemin | scalemax | scaleinc | separator | size | pipe | withpipe)+>
<!ELEMENT prompt (#PCDATA)>
<!ELEMENT format (language, code)+>
<!ELEMENT vdef ((value)+ | (language, code)+)>
<!ELEMENT group (#PCDATA)>
<!ELEMENT info (#PCDATA)>
<!ELEMENT vlist (value, label)+>
<!ELEMENT flist (value, code)+>
<!ELEMENT comment (value)+>
<!ELEMENT seqfmt (value)+>
<!ELEMENT seqtype (value | (language, code)+)>
<!ELEMENT ctrls (ctrl)+>
<!ELEMENT ctrl (message, (language, code)+)>
<!ELEMENT warns (warn)+>
<!ELEMENT warn (message, (language, code)+)>
<!ELEMENT message (#PCDATA)>
<!ELEMENT precond (language, code)+>
<!ELEMENT paramfile (#PCDATA)>
<!ELEMENT filenames (#PCDATA)>
<!ELEMENT scalemin (value | (language, code)+)>
<!ELEMENT scalemax (value | (language, code)+)>
<!ELEMENT scaleinc (#PCDATA)>
<!ELEMENT separator (#PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT pipe (pipetype, (language, code)+)+>
<!ELEMENT withpipe (pipetype, (parametername)+)+>
<!ELEMENT parametername (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT pipetype (#PCDATA)>
<!ELEMENT label (#PCDATA)>
<!ELEMENT language (#PCDATA)>

=== cianfrocco-lab/COSMIC-CryoEM-Gateway/gateway_config/sdk/src/main/resources/pisexml/ardecon.xml
<?xml version = "1.0" encoding = "UTF-8" ?>
<!DOCTYPE pise PUBLIC "pise2.dtd" "pise2.dtd"  [
<!ENTITY runtime_tg PUBLIC "run_time2.xml.in" "run_time2.xml.in" >
]>
<!-- Created by Mark Miller for CryoEM project around 5/24/2016-->
<pise>
  <head>
    <title>ARDECON</title>
    <version>1.0</version>
    <description>Deconvolution to restore cryo-EM maps with anisotropic resolution.</description>
    <authors>Li J, Chen Y, Zheng S, McDonald A, Sedat JW, Agard DA, Cheng Y</authors>
    <reference>https://www.biorxiv.org/content/10.1101/2025.02.23.639707v1</reference>
    <category>Validation and Analysis</category>
    <doclink>https://github.com/yifancheng-ucsf/AR-Decon</doclink>
  </head>

  <command>ardecon</command>

<parameters>
<!-- command name: this parameter precedes all instruction strings -->
    <parameter ishidden="1" type="String"> 
	  <name>relion_invoke</name>
	  <attributes>
	    <format>
		  <language>perl</language>
		  <code>"ardecon"</code>
		</format>
		<group>0</group>
	  </attributes>
	</parameter> 
	  
<!-- build the conf file -->
	<parameter ishidden="1" type="String">
		<name>relion_scheduler</name>
		<attributes>
			<paramfile>scheduler.conf</paramfile>
			<format>
				<language>perl</language>
				<code>
<!-- RUN THESE JOBS ON Comet -->
				 "runhours=1\\n" . 
			     "ntasks-per-node=1\\n" .
				 "nodes=1\\n"
				</code>
			</format>
			<group>1</group>
		</attributes>
	</parameter>	

<!-- create the non-configurable command line -->
<!--  -->
	<parameter ishidden="1" type="String">
		<name>relion_commandline</name>
		<attributes>
			<group>1</group>
		</attributes>
	</parameter>	

<!-- required input file, this is selected outside the parameters gui -->
    <parameter isinput = "1" type = "InFile">
	  <name>infile</name>
	  <attributes>
	    <prompt>3D reconstruction MRC file (full map; NOT sharpened)</prompt>
		<format>
		  <language>perl</language>
		  <code>"\"-i=$value\""</code>
		</format>
	    <group>90</group>
	  </attributes>	  
	</parameter>

	<parameter type="InFile" issimple="1" ismandatory="1">
        <name>half1</name>
        <attributes>
            <group>1</group>
            <prompt>Half map #1</prompt>
            <format>
                <language>perl</language>
                <code>"-i1=$value"</code>
            </format>
        </attributes>
    </parameter>

	<parameter type="InFile" issimple="1" ismandatory="1">
        <name>half2</name>
        <attributes>
            <group>1</group>
            <prompt>Half map #2.</prompt>
            <format>
                <language>perl</language>
                <code>"-i2=$value"</code>
            </format>
        </attributes>
    </parameter>

	<parameter type="InFile" issimple="1">
        <name>mask</name>
        <attributes>
            <group>1</group>
            <prompt>(Optional) Provide mask</prompt>
            <format>
                <language>perl</language>
                <code>"-m=$value"</code>
            </format>
        </attributes>
    </parameter>

	<parameter type="Float">
        <name>sigma</name>
        <attributes>
            <group>1</group>
            <prompt>Sigma value for generating OTF (default: auto-calculated).</prompt>
            <format>
                <language>perl</language>
                <code>"-sigma=$value"</code>
            </format>
        </attributes>
    </parameter>	

	<parameter type="Float" ismandatory="1">
        <name>smooth</name>
        <attributes>
            <group>1</group>
            <prompt>Smoothing parameter for deconvolution (default: 0.5).</prompt>
            <format>
                <language>perl</language>
                <code>"-smooth=$value"</code>
            </format>
			<vdef>
                <value>0.5</value>
            </vdef>
        </attributes>
    </parameter>
	
	<parameter type="Integer" ismandatory="1">
        <name>nonlin</name>
        <attributes>
            <group>1</group>
            <prompt>Nonlinearity parameter for deconvolution (default: 10000).</prompt>
            <format>
                <language>perl</language>
                <code>"-nonlin=$value"</code>
            </format>
            <vdef>
                <value>10000</value>
            </vdef>
        </attributes>
    </parameter>

	
<!-- Files to transfer back -->
	<parameter type="Results">
      <name>AR-DECON results</name>
      <attributes>
        <filenames>ardecon/*</filenames>
      </attributes>
    </parameter>
<!-- visible input parameters -->	

</parameters>

</pise>

=== cianfrocco-lab/COSMIC-CryoEM-Gateway/gateway_config/sdk/src/main/resources/pisexml/alphafold2.xml
<?xml version = "1.0" encoding = "UTF-8" ?>
<!DOCTYPE pise PUBLIC "pise2.dtd" "pise2.dtd"  [
<!ENTITY runtime_tg PUBLIC "run_time2.xml.in" "run_time2.xml.in" >
]>
<!-- Created by Mark Miller for CryoEM project around 5/24/2016-->
<pise>
  <head>
    <title>AlphaFold2</title>
    <!-- from https://github.com/prehensilecode/alphafold_singularity -->
    <version>2.3.1</version>
    <description>Highly accurate protein structure prediction</description>
    <authors>Jumper et al. </authors>
    <reference>https://www.nature.com/articles/s41586-021-03819-2</reference>
    <category>Protein structure prediction</category>
    <doclink>https://github.com/deepmind/alphafold</doclink>
  </head>

  <command>alphafold2</command>

<parameters>
<!-- command name: this parameter precedes all instruction strings -->
    <parameter ishidden="1" type="String"> 
	  <name>relion_invoke</name>
	  <attributes>
	    <format>
		  <language>perl</language>
		  <code>"alphafold2"</code>
		</format>
		<group>0</group>
	  </attributes>
	</parameter> 
	  
<!-- build the conf file -->
	<parameter ishidden="1" type="String">
		<name>relion_scheduler</name>
		<attributes>
			<paramfile>scheduler.conf</paramfile>
			<format>
				<language>perl</language>
				<code>
<!-- RUN THESE JOBS ON Comet -->
				 "gpu=4\\n" . 
				 "runhours=48\\n" . 
			     "ntasks-per-node=1\\n" .
				 "nodes=1\\n"
				</code>
			</format>
			<group>1</group>
		</attributes>
	</parameter>	

<!-- create the non-configurable command line -->
<!--  -->
	<parameter ishidden="1" type="String">
		<name>relion_commandline</name>
		<attributes>
			<group>1</group>
		</attributes>
	</parameter>	

<!-- required input file, this is selected outside the parameters gui -->
    <parameter isinput = "1" type = "InFile">
	  <name>infile</name>
	  <attributes>
	    <prompt>FASTA file</prompt>
		<format>
		  <language>perl</language>
		  <code>"--fasta_paths=\"$value\""</code>
		</format>
	    <group>90</group>
	  </attributes>	  
	</parameter>
	
    <parameter type="Results">
      <name>stderr.txt</name>
      <attributes>
        <filenames>stderr</filenames>
      </attributes>
    </parameter>

	<parameter type="Results">
      <name>Input FASTA file</name>
      <attributes>
        <filenames>*.fasta</filenames>
      </attributes>
    </parameter>

    <parameter type="Results">
      <name>Predicted structural models</name>
      <attributes>
        <filenames>output_dir/*/*relaxed*pdb</filenames>
      </attributes>
    </parameter>

	<parameter type="Results">
      <name>Diagnostic plots for each predicted model</name>
      <attributes>
        <filenames>output_dir/*/*.png</filenames>
      </attributes>
    </parameter>

	<parameter type="Results">
      <name>Full output from AlphaFold (compressed)</name>
      <attributes>
        <filenames>*.tar.gz</filenames>
      </attributes>
    </parameter>

	<parameter type="Results">
      <name>Ranking of AlphaFold models</name>
      <attributes>
        <filenames>output_dir/*/*anking_debug.json</filenames>
      </attributes>
    </parameter>

<!-- visible input parameters -->	

	<parameter type="Integer" issimple="1" ismandatory="1">
	    <name>num_multimer_predictions_per_model</name>
	    <attributes>
		    <group>1</group>
		    <prompt>Number of predictions per model</prompt>
		    <format>
			    <language>perl</language>
			    <code>"--num_multimer_predictions_per_model=$value"</code>
		    </format>
            <vdef>
                <value>5</value>
            </vdef>
	    </attributes>
    </parameter>
	<parameter type="String" issimple="0" ismandatory="0">
	    <name>max_template_date</name>
	    <attributes>
		    <group>1</group>
		    <prompt>Latest date (YYYY-mm-dd) to use for template search (if using templates)</prompt>
		    <format>
			    <language>perl</language>
			    <code>"--max_template_date=$value"</code>
		    </format>
            <vdef>
                <value>2023-03-26</value>
            </vdef>
	    </attributes>
    </parameter>
	<parameter type="Excl" issimple="1" ismandatory="1">
	    <name>db_preset</name>
	    <attributes>
		    <group>1</group>
		    <prompt>Database</prompt>
		    <format>
			    <language>perl</language>
			    <code>"--db_preset=$value"</code>
		    </format>
            <vdef>
                <value>full_dbs</value>
            </vdef>
            <vlist>
                <value>reduced_dbs</value>
                <label>reduced_dbs</label>
                <value>full_dbs</value>
                <label>full_dbs</label>
            </vlist>
	    </attributes>
    </parameter>
	<parameter type="Excl" issimple="1" ismandatory="1" ishidden="0">
	    <name>model_preset</name>
	    <attributes>
		    <group>1</group>
		    <prompt>Model</prompt>
		    <format>
			    <language>perl</language>
			    <code>"--model_preset=$value"</code>
		    </format>
            <vlist>
                <value>monomer</value>
                <label>monomer</label>
                <value>monomer_ptm</value>
                <label>monomer_ptm</label>
				<vdef>
                	<value>monomer_ptm</value>
            	</vdef>
                <value>multimer</value>
                <label>multimer</label>
            </vlist>
	    </attributes>
    </parameter>
    <parameter type="Switch" issimple="0" ismandatory="0" ishidden="0">
        <name>skip_run_relax</name>
        <attributes>
            <group>1</group>
            <prompt>Skip calculating relaxed models</prompt>
            <format>
                <language>perl</language>
                <code>" --skip_run_relax=$value"</code>
            </format>
            <vdef>
                <value>1</value>
            </vdef>
        </attributes>
    </parameter>

</parameters>

</pise>

=== cianfrocco-lab/COSMIC-CryoEM-Gateway/gateway_config/sdk/src/main/resources/pisexml/esmfold.xml
<?xml version = "1.0" encoding = "UTF-8" ?>
<!DOCTYPE pise PUBLIC "pise2.dtd" "pise2.dtd"  [
<!ENTITY runtime_tg PUBLIC "run_time2.xml.in" "run_time2.xml.in" >
]>
<!-- Created by Mark Miller for CryoEM project around 5/24/2016-->
<!--
@article{ruffolo2021deciphering,
    title = {Deciphering antibody affinity maturation with language models and weakly supervised learning},
    author = {Ruffolo, Jeffrey A and Gray, Jeffrey J and Sulam, Jeremias},
    journal = {arXiv},
    year= {2021}
}
@article{ruffolo2022fast,
    title = {Fast, accurate antibody structure prediction from deep learning on massive set of natural antibodies},
    author = {Ruffolo, Jeffrey A and Chu, Lee-Shin and Mahajan, Sai Pooja and Gray, Jeffrey J},
    journal = {bioRxiv},
    year= {2022}
}
 -->

<pise>
  <head>
    <title>ESMFold</title>
    <version>1.0.3</version>
    <description>Evolutionary-scale prediction of atomic level protein structure with a language model</description>
    <authors>Lin et al. </authors>
    <reference>https://www.science.org/doi/10.1126/science.ade2574</reference>
    <category>Protein structure prediction</category>
    <doclink>https://github.com/graylab/igfold</doclink>
  </head>

  <command>esmfold</command>

<parameters>
<!-- command name: this parameter precedes all instruction strings -->
    <parameter ishidden="1" type="String"> 
	  <name>relion_invoke</name>
	  <attributes>
	    <format>
		  <language>perl</language>
		  <code>"esmfold"</code>
		</format>
		<group>0</group>
	  </attributes>
	</parameter> 
	  
<!-- build the conf file -->
	<parameter ishidden="1" type="String">
		<name>relion_scheduler</name>
		<attributes>
			<paramfile>scheduler.conf</paramfile>
			<format>
				<language>perl</language>
				<code>
<!-- RUN THESE JOBS ON Comet -->
				 "cpus=1\\n" . 
				 "memory=2G\\n" . 
				 "runhours=1\\n" . 
			     "ntasks-per-node=1\\n" .
				 "nodes=1\\n"
				</code>
			</format>
			<group>1</group>
		</attributes>
	</parameter>	

<!-- create the non-configurable command line -->
<!--  -->
	<parameter ishidden="1" type="String">
		<name>relion_commandline</name>
		<attributes>
			<group>1</group>
		</attributes>
	</parameter>	

<!-- required input file, this is selected outside the parameters gui -->
    <parameter isinput = "1" type = "InFile">
	  <name>infile</name>
	  <attributes>
	    <prompt>FASTA file</prompt>
		<format>
		  <language>perl</language>
		  <code>"--fasta_path=\"$value\""</code>
		</format>
	    <group>90</group>
	  </attributes>	  
	</parameter>

	<parameter type="Integer" issimple="1" ismandatory="1">
      <name>num_recycles</name>
      <attributes>
        <group>1</group>
        <prompt>Number of Recycles</prompt>
        <format>
          <language>perl</language>
          <code>"--num_recycles=$value"</code>
        </format>
        <vdef>
          <value>4</value>
        </vdef>
        <ctrls>
          <ctrl>
            <message>Please enter an integer > 0 for the number of recycles to use</message>
            <language>perl</language>
            <code>$num_recycles &lt; 0</code>
          </ctrl>
        </ctrls>
      </attributes>
    </parameter>

	<parameter type="Excl" issimple="1" >
        <name>chunk</name>
        <attributes>
            <group>1</group>
            <prompt>Chunk size for axial attention. Use to reduce memory footprint, smaller numbers uses less memory at the cost of speed.</prompt>
            <format>
                <language>perl</language>
                <code>"--chunk=$chunk"</code>
            </format>
            <vlist>
                <value>-1</value>
                <label>-1</label>
                <value>128</value>
                <label>128</label>
                <value>64</value>
                <label>64</label>
                <value>32</value>
                <label>32</label>
                <value>16</value>
                <label>16</label>
                <value>8</value>
                <label>8</label>
            </vlist>
        </attributes>
    </parameter>
	
    <parameter type="Results">
      <name>stderr.txt</name>
      <attributes>
        <filenames>stderr</filenames>
      </attributes>
    </parameter>

	<parameter type="Results">
      <name>Input FASTA file</name>
      <attributes>
        <filenames>*.fasta</filenames>
      </attributes>
    </parameter>

	<parameter type="Results">
      <name>PDB file</name>
      <attributes>
        <filenames>*.pdb</filenames>
      </attributes>
    </parameter>
	<parameter type="Results">
      <name>Diagnostic plots for each predicted model</name>
      <attributes>
        <filenames>*.png</filenames>
      </attributes>
    </parameter>



<!--
	<parameter type="Results">
      <name>A3M</name>
      <attributes>
        <filenames>output_dir/*.a3m</filenames>
      </attributes>
    </parameter>
 -->

<!-- visible input parameters -->	


</parameters>

</pise>

=== cianfrocco-lab/COSMIC-CryoEM-Gateway/gateway_config/sdk/src/main/resources/pisexml/relion_postprocess.xml
<?xml version = "1.0" encoding = "UTF-8" ?>
<!DOCTYPE pise PUBLIC "pise2.dtd" "pise2.dtd"  [
<!ENTITY runtime_tg PUBLIC "run_time2.xml.in" "run_time2.xml.in" >
]>
<!-- Created by Mark Miller for CryoEM project around 5/24/2016-->
<pise>
  <head>
    <title>RELION Postprocess</title>
    <version>3.1</version>
    <description>Sharpen and filter 3D reconstruction using RELION</description>
    <authors>S. H. W. Scheres</authors>
<!--
    <reference>Scheres, S. H. W. (2012) RELION: Implementation of a Bayesian approach to cryo-EM structure determination. Journal of Structural Biology 180, 519-530</reference>
 -->
	<reference>http://www.sciencedirect.com/science/article/pii/S104784771200248
1</reference>
    <category>RELION</category>
    <doclink>http://www2.mrc-lmb.cam.ac.uk/relion/index.php/Main_Page</doclink>
  </head>

  <command>relion_postprocess</command>
<!-- 
Per our conversation earlier today, I’m sending along a comet submission script for the analysis routine that will be a part of the gateway. 

First, you can look at an example submission script that I typically have used (‘relion_refine_submission.txt’). The cluster input variables are standard, 
and then there is a single command that will run using MPI. 

The barebones version of the command line input is the following (‘relion_refine_submission_base.txt’). I’ve bolded and underlined the areas that users 
will have to input: 

ibrun -v relion_refine_mpi  —o /path/to/working/directory/[output] -*auto_refine -*split_random_halves —i /path/to/working/directory/[input file] 
-*particle_diameter [user provided] —angpix [user provided] —ref /path/to/working/directory/[user provided] -*ini_high [user provided] -*ctf 
-*flatten_solvent -*zero_mask -*oversampling 1 -*healpix_order 2 -*auto_local_healpix_order 4 -*offset_range [user provided] -*offset_step [user provided] 
—sym [user provided] -*low_resol_join_halves 40 -*norm -*scale  -*j 1 -*memory_per_thread 4

A list of variables that I would change for these test run (or at least an initial list of variables):
—o Output file basename
—i Input file
—particle_diameter Diameter of particle (Angstroms)
—angpix Pixel size of data (A/pix)
—ref 3D model to use as template 
—ini_high Initial filter for 3D volume
—offset_range Pixel search range 
—offset_step Pixel search range step size
—sym Symmetry of sample 
I’m not sure what the next steps are for building out this command, but this is a definite start. There will be a few added changes to the submission command based upon users data, which we will incorporate into the gateway job template page.



Let me know what else I can do to help!
Mike -->

<parameters>
<!-- command name: this parameter precedes all instruction strings -->
    <parameter ishidden="1" type="String"> 
	  <name>relion_invoke</name>
	  <attributes>
	    <format>
		  <language>perl</language>
		  <code>"relion_postprocess"</code>
		</format>
		<group>0</group>
	  </attributes>
	</parameter> 
	  
<!-- build the conf file -->
	<parameter ishidden="1" type="String">
		<name>relion_scheduler</name>
		<attributes>
			<paramfile>scheduler.conf</paramfile>
			<format>
				<language>perl</language>
				<code>
<!-- RUN THESE JOBS ON Comet -->
                 "runhours=1\\n" .
                 "ChargeFactor=1.0\\n" .
                 "ntasks-per-node=1\\n" .
                 "cores_per_node=1\\n" .
                 "nodes=1\\n"
				</code>
			</format>
			<group>1</group>
		</attributes>
	</parameter>	

	<parameter isinput = "1" type = "InFile">
      <name>infile</name>
      <attributes>
        <prompt>3D reconstruction MRC file (half map 1; NOT sharpened)</prompt>
        <format>
          <language>perl</language>
          <code>"--i \"$value\""</code>
        </format>
        <group>90</group>
      </attributes>
    </parameter>

	<parameter type="Results">
      <name>stderr.txt</name>
      <attributes>
        <filenames>stderr</filenames>
      </attributes>
    </parameter>

	<parameter type="Results">
      <name>Sharpened map</name>
      <attributes>
        <filenames>postprocess.mrc</filenames>
      </attributes>
    </parameter>

	<parameter type="Results">
      <name>Postprocess STAR file</name>
      <attributes>
        <filenames>postprocess.star</filenames>
      </attributes>
    </parameter>

	<parameter type="InFile" issimple="1" ismandatory="1">
        <name>half2</name>
        <attributes>
            <group>1</group>
            <prompt>3D reconstruction MRC file (half map 2; NOT sharpened)</prompt>
            <format>
                <language>perl</language>
                <code>"--i2 $value"</code>
            </format>
            <ctrls>
                <ctrl>
                    <message>Please choose a 3D volume</message>
                    <language>perl</language>
                    <code>!$half2</code>
                </ctrl>
            </ctrls>
        </attributes>
    </parameter>

	<parameter type="InFile" issimple="1" ismandatory="1">
        <name>mask</name>
        <attributes>
            <group>1</group>
            <prompt>3D mask MRC file</prompt>
            <format>
                <language>perl</language> 
                <code>"--mask $value"</code>
            </format>
            <ctrls>
                <ctrl>
                    <message>Please choose a 3D volume</message>
                    <language>perl</language>
                    <code>!$mask</code>
                </ctrl>
            </ctrls>
        </attributes>
    </parameter>

	<parameter type="InFile">
        <name>mtf</name>
        <attributes>
            <group>1</group>
            <prompt>MTF of the detector (STAR file) (Optional)</prompt>
            <format>
                <language>perl</language>
                <code>"--mtf $value"</code>
            </format>
        </attributes>
    </parameter>

	<parameter type="Float" ismandatory="1" issimple="1">
        <name>angpix</name>
        <attributes>
            <group>1</group>
            <prompt>Pixel size of reconstruction (Angstroms/pixel)</prompt>
            <format>
                <language>perl</language>
                <code>"--angpix $value"</code>
            </format>
            <ctrls>
                <ctrl>
                    <message>Please enter a float > 0.00 for the pixel size (in Angstroms/pix)</message>
                    <language>perl</language>
                    <code>$angpix &lt; 0.01</code>
                </ctrl>
            </ctrls>
        </attributes>
    </parameter>

	<parameter type="Float" >
        <name>orig_angpix</name>
        <attributes>
            <group>1</group>
            <prompt>Original detector pixel size (Angstroms/pixel)</prompt>
            <format>
                <language>perl</language>
                <code>"--mtf_angpix $value"</code>
            </format>
        </attributes>
    </parameter>

	<parameter type="Float">
        <name>skip_filt</name>
        <attributes>
            <group>1</group>
            <prompt>Ad-hoc low pass filter (if provided, will skip FSC-weighting)</prompt>
            <format>
                <language>perl</language>
                <code>"--skip_fsc_weighting --lowpass $value"</code>
            </format>
        </attributes>
    </parameter>	
	
    <parameter type="Integer">
	    <name>bfactor_res</name>
	    <attributes>
		    <group>1</group>
		    <prompt>Lowest resolution for automatic B-factor estimation</prompt>
		    <format>
			    <language>perl</language>
			    <code>"--autob_lowres $value"</code>
		    </format>
			<vdef>
                <value>10</value>
            </vdef>
		    <ctrls>
			    <ctrl>
                    <message>Please enter an integer > 0</message>
				    <language>perl</language>
				    <code>$bfactor_res &lt; 1</code>
			    </ctrl>
		    </ctrls>
	    </attributes>
    </parameter>

    <parameter type="Integer" >
        <name>ownbfactor</name>
        <attributes>
            <group>1</group>
            <prompt>User-provided B-factor (if provided, it will override automatic B-factor)</prompt>
            <format>
                <language>perl</language>
                <code>"--adhoc_bfac $value"</code>
            </format>
            <ctrls>
                <ctrl>
                    <message>B-factors for sharpening should be negative. Please enter an integer less than 0</message>
                    <language>perl</language>
                    <code>$ownbfactor &gt; 0</code>
                </ctrl>
            </ctrls>
        </attributes>
    </parameter>

</parameters>

</pise>
