=== cianfrocco-lab/COSMIC-CryoEM-Gateway/gateway_config/sdk/src/main/resources/pisexml/pise2.dtd
<!-- DTD for Pise descriptions
     Copyright (C) 1999-2204 Institut Pasteur and Catherine Letondal <letondal@pasteur.fr> 
  -->
<!ENTITY % word "CDATA">
<!ENTITY % number "CDATA">
<!ENTITY % boolean "CDATA">
<!ELEMENT pise (head, command, parameters)>
<!ELEMENT command (#PCDATA)>
<!ELEMENT parameters (parameter)+>
<!ELEMENT head (title, version?, description?, authors?, reference*, category*, doclink*)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT doclink (#PCDATA)>
<!ELEMENT authors (#PCDATA)>
<!ELEMENT reference (#PCDATA)>
<!ELEMENT parameter (paragraph | (name, attributes)+)>
<!ELEMENT paragraph (name, prompt, precond?, group?, format?, comment?, parameters)>
<!ATTLIST parameter
	type (InFile | Sequence | OutFile | Results | Switch | Excl | List | Integer | Float | String | Paragraph | Label) #REQUIRED
	ismandatory %boolean; #IMPLIED
	iscommand %boolean; #IMPLIED
	ishidden %boolean; #IMPLIED
	isstandout %boolean; #IMPLIED
	issimple %boolean; #IMPLIED
	isclean %boolean; #IMPLIED
	isinput %boolean; #IMPLIED
>
<!ELEMENT attributes (prompt | info | format | vdef | group | vlist | flist | comment | seqfmt | seqtype | ctrls | warns | precond | paramfile | filenames | scalemin | scalemax | scaleinc | separator | size | pipe | withpipe)+>
<!ELEMENT prompt (#PCDATA)>
<!ELEMENT format (language, code)+>
<!ELEMENT vdef ((value)+ | (language, code)+)>
<!ELEMENT group (#PCDATA)>
<!ELEMENT info (#PCDATA)>
<!ELEMENT vlist (value, label)+>
<!ELEMENT flist (value, code)+>
<!ELEMENT comment (value)+>
<!ELEMENT seqfmt (value)+>
<!ELEMENT seqtype (value | (language, code)+)>
<!ELEMENT ctrls (ctrl)+>
<!ELEMENT ctrl (message, (language, code)+)>
<!ELEMENT warns (warn)+>
<!ELEMENT warn (message, (language, code)+)>
<!ELEMENT message (#PCDATA)>
<!ELEMENT precond (language, code)+>
<!ELEMENT paramfile (#PCDATA)>
<!ELEMENT filenames (#PCDATA)>
<!ELEMENT scalemin (value | (language, code)+)>
<!ELEMENT scalemax (value | (language, code)+)>
<!ELEMENT scaleinc (#PCDATA)>
<!ELEMENT separator (#PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT pipe (pipetype, (language, code)+)+>
<!ELEMENT withpipe (pipetype, (parametername)+)+>
<!ELEMENT parametername (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT pipetype (#PCDATA)>
<!ELEMENT label (#PCDATA)>
<!ELEMENT language (#PCDATA)>

=== cianfrocco-lab/COSMIC-CryoEM-Gateway/gateway_config/sdk/src/main/resources/pisexml/omegafold.xml
<?xml version = "1.0" encoding = "UTF-8" ?>
<!DOCTYPE pise PUBLIC "pise2.dtd" "pise2.dtd"  [
<!ENTITY runtime_tg PUBLIC "run_time2.xml.in" "run_time2.xml.in" >
]>
<!-- Created by Mark Miller for CryoEM project around 5/24/2016-->
<pise>
  <head>
    <title>OmegaFold</title>
    <version>1.0.2</version>
    <description>High-resolution de novo Structure Prediction from Primary Sequence</description>
    <authors>Ruidong Wu, Fan Ding, Rui Wang, Rui Shen, Xiwen Zhang, Shitong Luo, Chenpeng Su, Zuofan Wu, Qi Xie, Bonnie Berger, Jianzhu Ma, Jian Peng </authors>
    <reference>https://www.nature.com/articles/s41586-021-03819-2</reference>
    <category>Protein structure prediction</category>
    <doclink>https://github.com/deepmind/alphafold</doclink>
  </head>

  <command>omegafold</command>

<parameters>
<!-- command name: this parameter precedes all instruction strings -->
    <parameter ishidden="1" type="String"> 
	  <name>relion_invoke</name>
	  <attributes>
	    <format>
		  <language>perl</language>
		  <code>"omegafold"</code>

		</format>
		<group>0</group>
	  </attributes>
	</parameter> 
	  
<!-- build the conf file -->
	<parameter ishidden="1" type="String">
		<name>relion_scheduler</name>
		<attributes>
			<paramfile>scheduler.conf</paramfile>
			<format>
				<language>perl</language>
				<code>
<!-- RUN THESE JOBS ON Comet -->
				 "gpu=1\\n" . 
				 "runhours=1\\n" . 
			     "ntasks-per-node=1\\n" .
				 "nodes=1\\n"
				</code>
			</format>
			<group>1</group>
		</attributes>
	</parameter>	

<!-- create the non-configurable command line -->
<!--  -->
	<parameter ishidden="1" type="String">
		<name>relion_commandline</name>
		<attributes>
			<group>1</group>
		</attributes>
	</parameter>	

<!-- required input file, this is selected outside the parameters gui -->
    <parameter isinput = "1" type = "InFile">
	  <name>infile</name>
	  <attributes>
	    <prompt>FASTA file</prompt>
		<format>
		  <language>perl</language>
		  <code>"--fasta_paths=\"$value\""</code>
		</format>
	    <group>90</group>
	  </attributes>	  
	</parameter>
	
    <parameter type="Results">
      <name>stderr.txt</name>
      <attributes>
        <filenames>stderr</filenames>
      </attributes>
    </parameter>
	<parameter type="Integer">
      <name>num_cycles</name>
      <attributes>
        <group>1</group>
        <prompt>Number of cycles</prompt>
        <format>
          <language>perl</language>
          <code>"--num_cycle=$value"</code>
        </format>
        <vdef>
          <value>10</value>
        </vdef>
        <ctrls>
          <ctrl>
            <message>Please enter an integer > 0 for the number of cycles to use</message>
            <language>perl</language>
            <code>$num_cycles &lt; 0</code>
          </ctrl>
        </ctrls>
      </attributes>
    </parameter>

    <parameter type="Integer">
      <name>subbatch</name>
      <attributes>
        <group>1</group>
        <prompt>Subbatch size (size of sequence to use during prediction. Default = -1 is full sequence)</prompt>
        <format>
          <language>perl</language>
          <code>"--subbatch_size=$value"</code>
        </format>
        <vdef>
          <value>-1</value>
        </vdef>
      </attributes>
    </parameter>


	<parameter type="Results">
      <name>Input FASTA file</name>
      <attributes>
        <filenames>*.fasta</filenames>
      </attributes>
    </parameter>

    <parameter type="Results">
      <name>Predicted structural models</name>
      <attributes>
        <filenames>output_dir/*pdb</filenames>
      </attributes>
    </parameter>

</parameters>

</pise>

=== cianfrocco-lab/COSMIC-CryoEM-Gateway/gateway_config/sdk/src/main/resources/pisexml/auto_micassess.xml
<?xml version = "1.0" encoding = "UTF-8" ?>
<!DOCTYPE pise PUBLIC "pise2.dtd" "pise2.dtd"  [
<!ENTITY runtime_tg PUBLIC "run_time2.xml.in" "run_time2.xml.in" >
]>
<!-- Created by Mark Miller for CryoEM project around 5/24/2016-->
<pise>
  <head>
    <title>MicAssess</title>
    <version>0.1</version>
    <description>Automatically assess micrograph quality with deep learning.</description>
    <authors>Yilai Li and Michael Cianfrocco</authors>
    <reference>https://pubmed.ncbi.nlm.nih.gov/32294468/</reference>
    <category>Automated assessment tools</category>
    <doclink>https://www.biorxiv.org/content/10.1101/2019.12.20.885541v1.full</doclink>
  </head>

  <command>auto_micassess</command>

<parameters>
<!-- command name: this parameter precedes all instruction strings -->
    <parameter ishidden="1" type="String"> 
	  <name>relion_invoke</name>
	  <attributes>
	    <format>
		  <language>perl</language>
		  <code>"/home/cosmic2/software_dependencies/Automatic-cryoEM-preprocessing/micassess.py"</code>
		</format>
		<group>0</group>
	  </attributes>
	</parameter> 
	  
<!-- build the conf file -->
	<parameter ishidden="1" type="String">
		<name>relion_scheduler</name>
		<attributes>
			<paramfile>scheduler.conf</paramfile>
			<format>
				<language>perl</language>
				<code>
<!-- RUN THESE JOBS ON Comet -->
				 "runhours=1\\n" . 
                 "ChargeFactor=1.0\\n" .
			     "ntasks-per-node=1\\n" .
				 "node_exclusive=1\\n" .
                 "cores_per_node=1\\n" .
				 "nodes=1\\n"
				</code>
			</format>
			<group>1</group>
		</attributes>
	</parameter>	

<!-- create the non-configurable command line -->
<!--  -->
	<parameter ishidden="1" type="String">
		<name>relion_commandline</name>
		<attributes>
			<group>1</group>
		</attributes>
	</parameter>	

<!-- required input file, this is selected outside the parameters gui -->
    <parameter isinput = "1" type = "InFile">
	  <name>infile</name>
	  <attributes>
	    <prompt>STAR file</prompt>
		<format>
		  <language>perl</language>
		  <code>'-i "$value"'</code>
		</format>
	    <group>90</group>
	  </attributes>	  
	</parameter>

	<parameter type="Float" issimple="1" ismandatory="1">
        <name>thresh</name>
        <attributes>
            <group>1</group>
            <prompt>Threshold for classification. Default is 0.1. Higher number will cause more good micrographs being classified as bad.</prompt>
            <format>
                <language>perl</language>
                <code>"-t $value"</code>
            </format>
            <vdef>
                <value>0.1</value>
            </vdef>
			<ctrls>
                <ctrl>
                    <message>Please enter a value > 0 for the threshold</message>
                    <language>perl</language>
                    <code>$thresh &lt; 0</code>
                </ctrl>
            </ctrls>
        </attributes>
    </parameter>


<!--

        <parameter ishidden="1" type="Integer" ismandatory="1" issimple="1">
            <name>seconds</name>
            <attributes>
                <prompt>Number of seconds to sleep</prompt>
                <format>
                    <language>perl</language>
                    <code>"$value"</code>
                </format>
                <vdef><value>10</value></vdef>
                <group>3</group>
            </attributes>
        </parameter>

 -->
	
<!-- Files to transfer back -->
	<parameter type="Results">
	  <name>Error log file</name>
	  <attributes>
	    <filenames>stderr</filenames>
	  </attributes>
	</parameter>
    <parameter type="Results">
        <name>STAR file output</name>
        <attributes>
            <filenames>*micassess_good.star</filenames>
        </attributes>
    </parameter>
	<parameter type="Results">
        <name>Good and bad micrograph JPG files</name>
        <attributes>
            <filenames>*.zip</filenames>
        </attributes>
    </parameter>
</parameters>

</pise>

=== cianfrocco-lab/COSMIC-CryoEM-Gateway/gateway_config/sdk/src/main/resources/pisexml/local_bfactor_sharpen.xml
<?xml version = "1.0" encoding = "UTF-8" ?>
<!DOCTYPE pise PUBLIC "pise2.dtd" "pise2.dtd"  [
<!ENTITY runtime_tg PUBLIC "run_time2.xml.in" "run_time2.xml.in" >
]>
<pise>
  <head>
    <title>LocBfactor Map Enhancement</title>
    <version>0.0</version>
    <description>Local computational methods to improve the interpretability and analysis of cryo-EM maps.</description>
    <authors>Kaur S, Gomez-Blanco J, Khalifa A, Adinarayanan S, Sanchez-Garcia R, Wrapp D, McLellan JS, Bui KH, Vargas J</authors>
    <reference>biorxiv.org/content/10.1101/2020.05.11.088013v2</reference>
    <category>Validation and Analysis</category>
    <doclink>https://github.com/1aviervargas/LocSpiral-LocBSharpen-LocBFactor-LocOccupancy</doclink>
  </head>

  <command>local_bfactor_sharpen</command>

<parameters>
<!-- command name: this parameter precedes all instruction strings -->
    <parameter ishidden="1" type="String"> 
	  <name>relion_invoke</name>
	  <attributes>
	    <format>
		  <language>perl</language>
		  <code>"local_bfactor_sharpen"</code>
		</format>
		<group>0</group>
	  </attributes>
	</parameter> 
	  
<!-- build the conf file -->
	<parameter ishidden="1" type="String">
		<name>relion_scheduler</name>
		<attributes>
			<paramfile>scheduler.conf</paramfile>
			<format>
				<language>perl</language>
				<code>
<!-- RUN THESE JOBS ON Comet -->
				 "runhours=1\\n" .
                 "ntasks-per-node=24\\n" .
                 "node_exclusive=1\\n" .
                 "nodes=1\\n"
				</code>
			</format>
			<group>1</group>
		</attributes>
	</parameter>

<!-- create the non-configurable command line -->
	<parameter ishidden="1" type="String">
		<name>relion_commandline</name>
		<attributes>
			<group>1</group>
		</attributes>
	</parameter>	

<!-- required input file, this is selected outside the parameters gui -->
    <parameter isinput = "1" type = "InFile">
	  <name>infile</name>
	  <attributes>
	    <prompt>Unfiltered half map 1 (unfiltered, not sharpened)</prompt>
		<format>
		  <language>perl</language>
		  <code>"--i \"$value\""</code>
		</format>
	    <group>90</group>
	  </attributes>	  
	</parameter>

	<parameter type="InFile" issimple="1">
        <name>half2</name>
        <attributes>
            <group>1</group>
            <prompt>Unfiltered half map 2 (unfiltered, not sharpened)</prompt>
            <format>
                <language>perl</language>
                <code>"--i2 $value"</code>
            </format>
        </attributes>
    </parameter>

	<parameter type="Float" ismandatory="1" issimple="1">
        <name>angpix</name>
        <attributes>
            <group>1</group>
            <prompt>Pixel size (Angstroms/pixel)</prompt>
            <format>
                <language>perl</language>
                <code>"--angpix $value"</code>
            </format>
            <ctrls>
                <ctrl>
                    <message>Please enter a float > 0.00 for the pixel size (in Angstroms/pix)</message>
                    <language>perl</language>
                    <code>$angpix &lt; 0.01</code>
                </ctrl>
            </ctrls>
        </attributes>
    </parameter>

    <parameter type="Float" ismandatory="1" issimple="1">
        <name>thresh</name>
        <attributes>
            <group>1</group>
            <prompt>Threshold to use for creating 3D mask from input half maps (from Chimera)</prompt>
            <format>
                <language>perl</language>
                <code>"--thresh $value"</code>
            </format>
        </attributes>
    </parameter>

	<parameter type="Float" ismandatory="1" issimple="1">
        <name>bhigh</name>
        <attributes>
            <group>1</group>
            <prompt>High resolution limit (global FSC resolution)</prompt>
            <format>
                <language>perl</language>
                <code>"--bfactor_max $value"</code>
            </format>
        </attributes>
    </parameter>

    <parameter type="Float" ismandatory="1">
        <name>bandwidth</name>
        <attributes>
            <group>1</group>
            <prompt>Bandwidth of the bandpass filter used in Fourier Space (Recommendations: If global resolution is less than 4A, use 3.5-5; If global resolution is greater than 4A, use 6-8)</prompt>
            <format>
                <language>perl</language>
                <code>"--bw $value"</code>
            </format>
            <vdef>
                <value>4.8</value>
            </vdef>
        </attributes>
    </parameter>

    <parameter type="Integer" ismandatory="1">
        <name>blow</name>
        <attributes>
            <group>1</group>
            <prompt>Advanced: Low resolution limit (Usually a value of 15-10 Angstroms works)</prompt>
            <format>
                <language>perl</language>
                <code>"--bfactor_min $value"</code>
            </format>
            <vdef>
                <value>15</value>
            </vdef>
        </attributes>
    </parameter>
	<parameter type="Float" ismandatory="1">
        <name>noise</name>
        <attributes>
            <group>1</group>
            <prompt>Advanced: Threshold for noise significance comparison</prompt>
            <format>
                <language>perl</language>
                <code>"--noise $value"</code>
            </format>
            <vdef>
                <value>0.95</value>
            </vdef>
        </attributes>
    </parameter>

	<parameter type="Switch">
        <name>highmem</name>
        <attributes>
            <group>1</group>
            <prompt>Advanced: Check box if your job is crashing because of memory issues</prompt>
            <format>
                <language>perl</language>
                <code>($value) ? " --highmem" : ""</code>
            </format>
            <vdef>
                <value>0</value>
            </vdef>
        </attributes>
    </parameter>

<!-- Files to transfer back -->
	<parameter type="Results">
      <name>Scheduler standard error</name>
      <attributes>
        <filenames>scheduler_stderr.txt</filenames>
      </attributes>
    </parameter>
	<parameter type="Results">
      <name>LocBfactor output</name>
      <attributes>
        <filenames>*locBfactor*.mrc</filenames>
      </attributes>
    </parameter>
<!-- visible input parameters -->	

</parameters>

</pise>

=== cianfrocco-lab/COSMIC-CryoEM-Gateway/gateway_config/sdk/src/main/resources/pisexml/deepemhancer.xml
<?xml version = "1.0" encoding = "UTF-8" ?>
<!DOCTYPE pise PUBLIC "pise2.dtd" "pise2.dtd"  [
<!ENTITY runtime_tg PUBLIC "run_time2.xml.in" "run_time2.xml.in" >
]>
<!-- Created by Mark Miller for CryoEM project around 5/24/2016-->
<pise>
  <head>
    <title>DeepEMhancer</title>
    <version>1.0</version>
    <description>Non-linear post-processing of cryo-EM maps for local sharpening-like post-processing and automatic masking/denoising.</description>
    <authors>Sanchez-Garcia R, Gomez-Blanco J, Cuervo A, Carazo JM, Sorzano COS, Vargas J.</authors>
    <reference>Sanchez-Garcia R, Gomez-Blanco J, Cuervo A, Carazo JM, Sorzano COS, Vargas J. "DeepEMhancer: a deep learning solution for cryo-EM volume post-processing" bioRxiv (2020)</reference>
    <category>Validation and Analysis</category>
    <doclink>https://github.com/rsanchezgarc/deepEMhancer</doclink>
  </head>

  <command>deepemhancer</command>

<parameters>
<!-- command name: this parameter precedes all instruction strings -->
    <parameter ishidden="1" type="String"> 
	  <name>relion_invoke</name>
	  <attributes>
	    <format>
		  <language>perl</language>
		  <code>"deepemhancer"</code>
		</format>
		<group>0</group>
	  </attributes>
	</parameter> 
	  
<!-- build the conf file -->
	<parameter ishidden="1" type="String">
		<name>relion_scheduler</name>
		<attributes>
			<paramfile>scheduler.conf</paramfile>
			<format>
				<language>perl</language>
				<code>
<!-- RUN THESE JOBS ON Comet -->
				 "runhours=3\\n" . 
			     "ntasks-per-node=1\\n" .
				 "node_exclusive=1\\n" .
				 "nodes=1\\n"
				</code>
			</format>
			<group>1</group>
		</attributes>
	</parameter>	

<!-- create the non-configurable command line -->
<!--  -->
	<parameter ishidden="1" type="String">
		<name>relion_commandline</name>
		<attributes>
			<group>1</group>
		</attributes>
	</parameter>	

<!-- required input file, this is selected outside the parameters gui -->
    <parameter isinput = "1" type = "InFile">
	  <name>infile</name>
	  <attributes>
	    <prompt>3D reconstruction MRC file (full or half map; NOT sharpened)</prompt>
		<format>
		  <language>perl</language>
		  <code>"-i \"$value\""</code>
		</format>
	    <group>90</group>
	  </attributes>	  
	</parameter>

    <parameter type="Excl" issimple="1" ismandatory="1">
        <name>model</name>
        <attributes>
            <group>1</group>
            <prompt>Deep learning model to use for processing. Wide and tight target models were trained on maps with wider or tighter masks. HighRes was trained on maps less than 4A resolution</prompt>
            <format>
                <language>perl</language>
                <code>"-p $value"</code>
            </format>
            <vdef>
                <value>tightTarget</value>
            </vdef>
            <vlist>
                <value>wideTarget</value>
                <label>wideTarget</label>
                <value>tightTarget</value>
                <label>tightTarget</label>
				<value>highRes</value>
                <label>highRes</label>
			</vlist>
        </attributes>
    </parameter>
	
<!-- Files to transfer back -->
	<parameter type="Results">
      <name>Sharpened map</name>
      <attributes>
        <filenames>*deepEMhancer-sharpened.mrc</filenames>
      </attributes>
    </parameter>
<!-- visible input parameters -->	

</parameters>

</pise>

=== cianfrocco-lab/COSMIC-CryoEM-Gateway/gateway_config/sdk/src/main/resources/pisexml/modelangelo.xml
<?xml version = "1.0" encoding = "UTF-8" ?>
<!DOCTYPE pise PUBLIC "pise2.dtd" "pise2.dtd"  [
<!ENTITY runtime_tg PUBLIC "run_time2.xml.in" "run_time2.xml.in" >
]>
<!-- Created by Mark Miller for CryoEM project around 5/24/2016-->
<pise>
  <head>
    <title>Model Angelo</title>
    <version>1.0.1</version>
    <description>Automatic atomic model building program for cryo-EM maps</description>
    <authors>Jamali K, Kimanius D, Scheres S</authors>
    <reference>https://www.biorxiv.org/content/10.1101/2023.05.16.541002v1</reference>
    <category>Model building</category>
    <doclink>https://github.com/3dem/model-angelo</doclink>
  </head>

  <command>modelangelo</command>

<parameters>
<!-- command name: this parameter precedes all instruction strings -->
    <parameter ishidden="1" type="String"> 
	  <name>relion_invoke</name>
	  <attributes>
	    <format>
		  <language>perl</language>
		  <code>"model_angelo build"</code>
		</format>
		<group>0</group>
	  </attributes>
	</parameter> 
	  
<!-- build the conf file -->
	<parameter ishidden="1" type="String">
		<name>relion_scheduler</name>
		<attributes>
			<paramfile>scheduler.conf</paramfile>
			<format>
				<language>perl</language>
				<code>
<!-- RUN THESE JOBS ON Comet -->
				 "gpu=1\\n" .
				 "runhours=3\\n" . 
			     "ntasks-per-node=6\\n" .
				 "nodes=1\\n"
				</code>
			</format>
			<group>1</group>
		</attributes>
	</parameter>	

<!-- create the non-configurable command line -->
<!--  -->
	<parameter ishidden="1" type="String">
		<name>relion_commandline</name>
		<attributes>
			<group>1</group>
		</attributes>
	</parameter>	

<!-- required input file, this is selected outside the parameters gui -->
    <parameter isinput = "1" type = "InFile">
	  <name>infile</name>
	  <attributes>
	    <prompt>3D reconstruction (sharpened map)</prompt>
		<format>
		  <language>perl</language>
		  <code>"-v \"$value\""</code>
		</format>
	    <group>90</group>
	  </attributes>	  
	</parameter>

	<parameter type="InFile" issimple="1">
        <name>proteinfasta</name>
        <attributes>
            <group>1</group>
            <prompt>Protein fasta sequence</prompt>
            <format>
                <language>perl</language>
                <code>"-f $value"</code>
            </format>
        </attributes>
    </parameter>

	<parameter type="InFile" issimple="1">
        <name>dnafasta</name>
        <attributes>
            <group>1</group>
            <prompt>DNA fasta sequence</prompt>
            <format>
                <language>perl</language>
                <code>"-df $value"</code>
            </format>
        </attributes>
    </parameter>

	<parameter type="InFile" issimple="1">
        <name>rnafasta</name>
        <attributes>
            <group>1</group>
            <prompt>RNA fasta sequence</prompt>
            <format>
                <language>perl</language>
                <code>"-rf $value"</code>
            </format>
        </attributes>
    </parameter>

	<parameter type="InFile" issimple="1">
        <name>mask</name>
        <attributes>
            <group>1</group>
            <prompt>(Optional) Mask</prompt>
            <format>
                <language>perl</language>
                <code>"-m $value"</code>
            </format>
        </attributes>
    </parameter>

	<parameter type="Switch">
        <name>noseq</name>
        <attributes>
            <group>1</group>
            <prompt>Build model without input sequence)</prompt>
            <format>
                <language>perl</language>
                <code>($value) ? " build_no_seq" : ""</code>
            </format>
            <vdef>
                <value>0</value>
            </vdef>
        </attributes>
    </parameter>	

<!-- Files to transfer back -->
	<parameter type="Results">
      <name>Full output</name>
      <attributes>
        <filenames>output.zip</filenames>
      </attributes>
    </parameter>

	<parameter type="Results">
      <name>Built models</name>
      <attributes>
        <filenames>output/*.cif</filenames>
      </attributes>
    </parameter>

	<parameter type="Results">
      <name>Log file</name>
      <attributes>
        <filenames>output/model_angelo.log</filenames>
      </attributes>
    </parameter>
<!-- visible input parameters -->	

</parameters>

</pise>
